version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/ruby:3.4.2-browsers
  ubuntu_20-04-executor:
    machine:
      image: "ubuntu-2004:current"

jobs:
  build_artifact:
    parameters:
      parallelism_qty:
        type: integer
        default: 1
    parallelism: << parameters.parallelism_qty >>
    executor: ubuntu_20-04-executor
    steps:
      - checkout

  run-tests-on-docker:
    executor: docker-executor
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rspec spec/

  run-tests-on-ubuntu-2004:
    executor: ubuntu_20-04-executor
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rspec spec/

  test-web-site:
    docker:
      - image: "cimg/base:stable"
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - install-wget:
          version: "1.17.0-1ubuntu1"
      - run: wget --spider https://www.circleci.com

commands:
  install-wget:
    description: "Install the wget client"
    parameters:
      version:
        type: string
        default: "1.20.3-1ubuntu1"
    steps:
      - run: sudo apt install -y wget=<< parameters.version >>

workflows:
  build_workflow:
    jobs:
      - build_artifact:
          parallelism_qty: 2
  test-app-on-diff-os:
    jobs:
      - run-tests-on-docker
      - run-tests-on-ubuntu-2004
  run-tests:
    jobs:
      - test-web-site
